// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/lordtatty/llmeval"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJudge creates a new instance of MockJudge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJudge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJudge {
	mock := &MockJudge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJudge is an autogenerated mock type for the Judge type
type MockJudge struct {
	mock.Mock
}

type MockJudge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJudge) EXPECT() *MockJudge_Expecter {
	return &MockJudge_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockJudge
func (_mock *MockJudge) Evaluate(ctx context.Context, output string, criteria []llmeval.Criterion) ([]llmeval.CriterionResult, error) {
	ret := _mock.Called(ctx, output, criteria)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 []llmeval.CriterionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []llmeval.Criterion) ([]llmeval.CriterionResult, error)); ok {
		return returnFunc(ctx, output, criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []llmeval.Criterion) []llmeval.CriterionResult); ok {
		r0 = returnFunc(ctx, output, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]llmeval.CriterionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []llmeval.Criterion) error); ok {
		r1 = returnFunc(ctx, output, criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJudge_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockJudge_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - output string
//   - criteria []llmeval.Criterion
func (_e *MockJudge_Expecter) Evaluate(ctx interface{}, output interface{}, criteria interface{}) *MockJudge_Evaluate_Call {
	return &MockJudge_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, output, criteria)}
}

func (_c *MockJudge_Evaluate_Call) Run(run func(ctx context.Context, output string, criteria []llmeval.Criterion)) *MockJudge_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []llmeval.Criterion
		if args[2] != nil {
			arg2 = args[2].([]llmeval.Criterion)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJudge_Evaluate_Call) Return(criterionResults []llmeval.CriterionResult, err error) *MockJudge_Evaluate_Call {
	_c.Call.Return(criterionResults, err)
	return _c
}

func (_c *MockJudge_Evaluate_Call) RunAndReturn(run func(ctx context.Context, output string, criteria []llmeval.Criterion) ([]llmeval.CriterionResult, error)) *MockJudge_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}
